config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    resources :answers, only: [:create, :update]
  end
  resources :answers, only: :update

  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :body, presence: true, length: {minimum: 50}
  validates :question_id, presence: true

  belongs_to :question
  belongs_to :answer

  def body_html
    MarkdownRenderer.render(self.body)
  end

end

app/models/markdown_renderer.rb
class MarkdownRenderer
  def self.render(markdown)
    renderer = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true, fenced_code_blocks: true)
    renderer.render(markdown)
  end
end

app/models/question.rb
class Question < ActiveRecord::Base

  validates :title, presence: true, length: {minimum: 40}
  validates :body, presence: true, length: {minimum: 150}
  # validates :user_id, presence: true

  belongs_to :user
  has_many :answers

  def body_html
    MarkdownRenderer.render(self.body)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.question = @question
    @answer.user_id = session[:user_id]

    if @answer.save
      redirect_to "/questions/#{@question.id}"
    else
      flash.now[:notice] = "Unable to save your answer, please follow these requirements:"
      render :'questions/show'
    end
  end

  def update
    if @answer = Answer.where(best_answer: true).first
      @answer.best_answer = false
      @answer.save!
    end
    @answer = Answer.find(params[:id])
    @answer.best_answer = true
    @answer.save!
    redirect_to question_path(@answer.question_id)
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?, :authenticate!

  private

  def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in?
    current_user.present?
  end

  def authenticate!
    unless signed_in?
      flash[:notice] = 'You need to sign in to do that!'
      redirect_to questions_path
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.order(created_at: :desc)
  end

  def new
    authenticate!
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = session[:user_id]
    if @question.save
      redirect_to question_path(@question)
    else
      flash.now[:notice] = "Unable to submit your question, please follow these requirements:"
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
  end

  def update
    @question = Question.find(params[:id])

    if @question.update_attributes(question_params)
      redirect_to question_path(@question)
    else
      flash.now[:notice] = "Unable to submit your question, please follow these requirements:"
      render :'questions/edit'
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def destroy
    question = Question.find(params[:id])
    question.answers.each do |answer|
      answer.destroy
    end
    question.destroy
    flash[:notice] = "Your question was removed."
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to questions_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to questions_path, :notice => "Signed out!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RescueMission</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if signed_in? %>
      Signed in as <%= current_user.name %> |
      <%= link_to "Sign Out", signout_path %>
    <% else %>
      <%= link_to 'Sign In with Github', "auth/github" %>
    <% end %>
    <% if flash.any? %>
      <div>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/questions/edit.erb
<% if @question.errors.any? %>
  <ul>
    <% @question.errors.full_messages.each do |error| %>
      <li> <%= error %> </li>
    <% end %>
  </ul>
<% end %>

<%= form_for @question do |f| %>

  <strong>Title: </strong>
  <%= f.text_field :title %><br>

  <strong>Body: </strong>
  <%= f.text_area :body %><br>

  <%= f.submit %>
<% end %>

<br>
<%= link_to 'Back to Question', question_path(@question) %>
<br>
<%= link_to 'Back to All Questions', questions_path %>

app/views/questions/index.erb
<h2>Questions!</h2>
  <%= link_to 'Submit a Question', new_question_path %>
<br>
<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Created At</th>
  </tr>
  <% @questions.each do |question| %>
    <tr>
      <td>
        <%= link_to question.title, question_path(question) %>
      </td>
      <td><%= question.user.name %></td>
      <td><%= question.created_at %></td>
    </tr>
  <% end %>
</table>

app/views/questions/new.erb
<h2>Submit a New Question</h2>
<% if @question.errors.any? %>
  <ul>
    <% @question.errors.full_messages.each do |error| %>
      <li> <%= error %> </li>
    <% end %>
  </ul>
<% end %>

<%= form_for @question do |f| %>

  <strong>Title: </strong>
  <%= f.text_field :title %><br>

  <strong>Body: </strong>
  <%= f.text_area :body %><br>

  <%= f.hidden_field :user_id, value: session[:uid]%>

  <%= f.submit %>
<% end %>

<br>
<%= link_to 'Back to All Questions', questions_path %>

app/views/questions/show.erb
<h2><%= @question.title %></h2>

<p><%= @question.body_html.html_safe %></p>

Posted by: <%= @question.user.name %><br>

<br>
<%= form_for [@question, @answer] do |f| %>
  <%= f.label :body, "Answer this question:" %><br>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

<h3>Answers:</h3>
<ul>
  <% @question.answers.order(best_answer: :desc, created_at: :desc).each do |answer| %>
    <li>
      <% if answer.best_answer == true %>
        ***BEST ANSWER***
      <% end %>
      <%= answer.body_html.html_safe %>
      <% if session[:user_id] == @question.user_id %>
        <%= form_for answer do |f| %>
          <%= f.submit value: "Best Answer" %>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ul>

<br>
<% if signed_in? %>
  <% if session[:user_id] == @question.user_id %>
    <%= link_to 'Edit', edit_question_path(@question) %>
    <%= link_to 'Delete', question_path(@question), method: :delete %>
    <br>
  <% end %>
<% end %>
<%= link_to 'Back to All Questions', questions_path %>